 DATA PREPROCESSING

In [6]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [8]:
df=pd.read_excel("Online retail.xlsx",)
df.rename(columns={'Unnamed: 0' : "shrimp",'Unnamed: 1':'almonds','Unnamed: 2':'avocado','Unnamed: 3':'vegetables mix','Unnamed: 4':'green grapes','Unnamed: 5':'whole weat flour','Unnamed: 6':'yams','Unnamed: 7':'cottage cheese','Unnamed: 8':'energy drink','Unnamed: 9':'tomato juice','Unnamed: 10':'low fat yogurt','Unnamed: 11':'green tea','Unnamed: 12':'honey','Unnamed: 13':'salad','Unnamed: 14':'mineral water','Unnamed: 15':'salmon','Unnamed: 16':'antioxydant juice','Unnamed: 17':'frozen smoothie','Unnamed: 18':'spinach','Unnamed: 19':'olive oil'},inplace=True)
df

,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.fillna(0,inplace=True)

In [10]:
df=pd.get_dummies(df,dtype=int)
df

,shrimp_almonds,shrimp_antioxydant juice,shrimp_asparagus,shrimp_avocado,shrimp_babies food,shrimp_bacon,shrimp_barbecue sauce,shrimp_black tea,shrimp_blueberries,shrimp_body spray,...,frozen smoothie_0,frozen smoothie_frozen smoothie,frozen smoothie_protein bar,frozen smoothie_spinach,spinach_0,spinach_cereals,spinach_mayonnaise,spinach_spinach,olive oil_0,olive oil_olive oil
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
7497,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
7498,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
7499,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
7500,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0

In [11]:
df.duplicated().sum()

2325

In [12]:
df.drop_duplicates(inplace=True)
df

,shrimp_almonds,shrimp_antioxydant juice,shrimp_asparagus,shrimp_avocado,shrimp_babies food,shrimp_bacon,shrimp_barbecue sauce,shrimp_black tea,shrimp_blueberries,shrimp_body spray,...,frozen smoothie_0,frozen smoothie_frozen smoothie,frozen smoothie_protein bar,frozen smoothie_spinach,spinach_0,spinach_cereals,spinach_mayonnaise,spinach_spinach,olive oil_0,olive oil_olive oil
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,1
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7493,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
7494,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
7496,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
7497,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0
7500,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,1,0

In [13]:
df.isna().sum()

shrimp_almonds              0
shrimp_antioxydant juice    0
shrimp_asparagus            0
shrimp_avocado              0
shrimp_babies food          0
                           ..
spinach_cereals             0
spinach_mayonnaise          0
spinach_spinach             0
olive oil_0                 0
olive oil_olive oil         0
Length: 1288, dtype: int64

In [ ]:
APPLICATIONS OF APRIORI,ASS

In [14]:
from mlxtend.frequent_patterns import association_rules,apriori

In [15]:
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
frequent_itemsets

C:\Users\LENOVO\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

        support                                           itemsets
0      0.639876                               (whole weat flour_0)
1      0.735510                                           (yams_0)
2      0.810471                                 (cottage cheese_0)
3      0.873648                                   (energy drink_0)
4      0.923686                                   (tomato juice_0)
...         ...                                                ...
32762  0.639876  (whole weat flour_0, mineral water_0, salad_0,...
32763  0.639876  (whole weat flour_0, mineral water_0, salad_0,...
32764  0.639876  (whole weat flour_0, mineral water_0, salad_0,...
32765  0.735510  (mineral water_0, salad_0, low fat yogurt_0, s...
32766  0.639876  (whole weat flour_0, mineral water_0, salad_0,...

[32767 rows x 2 columns]

In [ ]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)
rules

In [ ]:
rules=rules.sort_values('lift',ascending=False)
rules.head()

In [31]:
# Interview Questions

1.Lift is the ratio of the observed support to that expected if A and B were independent. It indicates the strength of a rule over random co-occurrence.

 Lift(A → B) = Support(A ∪ B) / (Support(A) × Support(B))

2 .Support
Support is the proportion of transactions in the database in which the itemset appears. It indicates how frequently an itemset appears in the dataset.

Support(A) = Number of transactions containing A / Total number of transactions

Confidence
Confidence is the likelihood that a rule is correct for a new transaction containing the antecedent.

Confidence(A → B) = Support(A ∪ B) / Support(A)